name: Test and Lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22
      - name: Install dependencies
        run: go get -v ./...
      - name: Test with Go
        run: go test ./...
      - name: Vet with Go
        run: go vet ./...
      - name: Format Check
        run: |
          if ! gofmt -s -l .; then
            echo "Go code is not formatted correctly. Please run 'go fmt ./...'."
            exit 1
          fi
