name: Upload Go test results

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22
      - name: Install dependencies
        run: go get .
      - name: Test with Go
        run: go test ./... -json > TestResults-results.json
      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: Go-test-results
          path: TestResults-results.json
      - name: Vet with Go
        run: go vet -json > VetResults-results.json
      - name: Upload Go vet results
        uses: actions/upload-artifact@v4
        with:
          name: Go-vet-results
          path: VetResults-results.json
      - name: Format Check
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
